version: '3'

tasks:
  # Repo-wide maintenance
  tidy:
    desc: go mod tidy (repo root)
    cmds:
      - go mod tidy

  fmt:
    desc: go fmt ./...
    cmds:
      - go fmt ./...

  vet:
    desc: go vet ./...
    cmds:
      - go vet ./...

  test:
    desc: Run unit tests
    cmds:
      - go test ./...

  clean:
    desc: Remove build artifacts in examples
    cmds:
      - powershell -NoProfile -Command "if (Test-Path examples/counter/bin) { Remove-Item -Recurse -Force examples/counter/bin }"
      - powershell -NoProfile -Command "if (Test-Path examples/tree/bin) { Remove-Item -Recurse -Force examples/tree/bin }"

  # Examples
  examples:counter:run:
    desc: Run the counter example
    dir: examples/counter
    cmds:
      - go run .

  examples:counter:build:
    desc: Build the counter example binary
    dir: examples/counter
    cmds:
      - go build -o bin/counter .

  examples:crud:run:
    desc: Run the crud example
    dir: examples/crud
    cmds:
      - go run .

  examples:crud:build:
    desc: Build the crud example binary
    dir: examples/crud
    cmds:
      - go build -o bin/crud .

  examples:tree:run:
    desc: Run the tree example
    dir: examples/tree
    cmds:
      - go run .

  examples:tree:build:
    desc: Build the tree example binary
    dir: examples/tree
    cmds:
      - go build -o bin/tree .

  examples:websocket:run:
    desc: Run the websocket example
    dir: examples/websocket
    cmds:
      - go run .

  examples:websocket:build:
    desc: Build the websocket example binary
    dir: examples/websocket
    cmds:
      - go build -o bin/websocket .

  # default:
  #   desc: Alias to run counter example
  #   cmds:
  #     - task: examples:counter:run
